additionalRepositories:
  - url: https://github.com/jackbuehner/cristata-app
    checkoutLocation: cristata-app

tasks:
  - name: install dependencies (npm)
    init: |
      npm install
      gp sync-done npmi
      cd ../cristata-app
      npm install
      gp sync-done npmia
      exit

  - name: server
    init: gp sync-await npmi # wait for npm install to finish
    command: npm run dev
    openMode: tab-after
    env:
      PORT: 3000

  - name: app
    init: gp sync-await npmia # wait for npm install to finish
    command: cd ../cristata-app && npm run dev
    openMode: split-right # split terminal with server on left and app on right
    env:
      PORT: 4000
      REACT_APP_API_BASE_URL: 3000-$GITPOD_WORKSPACE_ID.$GITPOD_WORKSPACE_CLUSTER_HOST

ports:
  - port: 3000
    onOpen: ignore
    name: Cristata Server
    visibility: public
  - port: 4000
    onOpen: ignore
    name: Cristata App
    visibility: public

github:
  # configure continuous prebuilds for GitHub repositories
  prebuilds:
    # whether Gitpod creates prebuilds for the default branch
    master: true
    # whether Gitpod creates prebuilds for all branches
    branches: true
    # whether Gitpod creates prebuilds for pull requests from the original repository
    pullRequests: true
    # whether Gitpod creates prebuilds for pull requests from forks
    pullRequestsFromForks: false
    # whether Gitpod registers itself as a status check to pull requests
    addCheck: prevent-merge-on-error
    # add a comment with an “Open in Gitpod” button to your pull requests
    addComment: false
    # modify the description of a pull request to add an “Open in Gitpod” button (may cause concurrent editing conflicts)
    addBadge: true

vscode:
  extensions:
    - dbaeumer.vscode-eslint
    - tamasfe.even-better-toml
    - GitHub.vscode-pull-request-github
    - GraphQL.vscode-graphql
    - esbenp.prettier-vscode
    - eamodio.gitlens
    - vscode-icons-team.vscode-icons
    - aaron-bond.better-comments

workspaceLocation: cristata-api/.vscode/cristata.code-workspace
