name: Node.js Package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Cache node modules
        id: node-cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        if: steps.node-cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Run tests
        run: npm test
        env:
          MONGO_DB_USERNAME: ${{ secrets.MONGO_DB_USERNAME }}
          MONGO_DB_PASSWORD: ${{ secrets.MONGO_DB_PASSWORD }}
          MONGO_DB_HOST: ${{ secrets.MONGO_DB_HOST }}
          COOKIE_SESSION_SECRET: ${{ secrets.COOKIE_SESSION_SECRET }}

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/

      - name: Cache node modules
        id: node-cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        if: steps.node-cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Build
        run: npm run build
        env:
          MONGO_DB_USERNAME: ${{ secrets.MONGO_DB_USERNAME }}
          MONGO_DB_PASSWORD: ${{ secrets.MONGO_DB_PASSWORD }}
          MONGO_DB_HOST: ${{ secrets.MONGO_DB_HOST }}
          COOKIE_SESSION_SECRET: ${{ secrets.COOKIE_SESSION_SECRET }}

      # - name: Publish
      #   run: npm publish
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
