name: Node.js Package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: echo ${{ secrets.GITHUB_TOKEN }} && npm ci

      - name: Run tests
        run: npm test
        env:
          MONGO_DB_USERNAME: ${{ secrets.MONGO_DB_USERNAME }}
          MONGO_DB_PASSWORD: ${{ secrets.MONGO_DB_PASSWORD }}
          MONGO_DB_HOST: ${{ secrets.MONGO_DB_HOST }}
          COOKIE_SESSION_SECRET: ${{ secrets.COOKIE_SESSION_SECRET }}

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Create .env file
        uses: ozaytsev86/create-env-file@v1
        with:
          ENV_MONGO_DB_USERNAME: ${{ secrets.MONGO_DB_USERNAME }}
          ENV_MONGO_DB_PASSWORD: ${{ secrets.MONGO_DB_PASSWORD }}
          ENV_MONGO_DB_HOST: ${{ secrets.MONGO_DB_HOST }}
          ENV_COOKIE_SESSION_SECRET: ${{ secrets.COOKIE_SESSION_SECRET }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: npm run build

      - name: Publish
        run: npm publish
