name: CI

on: [push]

jobs:
  build:
    name: Build and Test
    timeout-minutes: 15
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
      TURBO_REMOTE_ONLY: true

    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Cache node modules
        id: node-cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}

      - name: Cache MongoDB binaries
        id: mongodb-cache
        uses: actions/cache@v2
        with:
          path: cache/mongodb-binaries
          key: mongodb-binaries-${{ hashFiles('cache/mongodb-binaries') }}

      - name: Install dependencies
        if: steps.node-cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Run tests
        run: npm test
        env:
          MONGO_DB_USERNAME: ${{ secrets.MONGO_DB_USERNAME }}
          MONGO_DB_PASSWORD: ${{ secrets.MONGO_DB_PASSWORD }}
          MONGO_DB_HOST: ${{ secrets.MONGO_DB_HOST }}
          COOKIE_SESSION_SECRET: ${{ secrets.COOKIE_SESSION_SECRET }}
