name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Cache node modules
        id: node-cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        if: steps.node-cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Create .env file
        uses: ozaytsev86/create-env-file@v1
        with:
          ENV_MONGO_DB_USERNAME: ${{ secrets.MONGO_DB_USERNAME }}
          ENV_MONGO_DB_PASSWORD: ${{ secrets.MONGO_DB_PASSWORD }}
          ENV_MONGO_DB_HOST: ${{ secrets.MONGO_DB_HOST }}
          ENV_COOKIE_SESSION_SECRET: ${{ secrets.COOKIE_SESSION_SECRET }}

      - name: Run tests
        run: npm test
